import java.sql.SQLOutput;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {
    private static String str = "Hello World";
    public String getGreeting() {
        return str;
    }
    public String getData(){return str;}
    public String getData1(){return str;}
    public String getData2(){return str;}

    public static void main(String[] args) {
        new App().getGreeting();
        new App().getData();
        new App().getData1();
        new App().getData2();
    }
}
